# Generated by Django 5.2 on 2025-04-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('approve_question', 'Puede aprobar preguntas'), ('feature_question', 'Puede destacar preguntas')]},
        ),
    ]
