# Generated by Django 5.2 on 2025-04-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_approve_article', 'Can approve article'), ('can_feature_article', 'Can feature article')]},
        ),
    ]
