# Generated by Django 5.2 on 2025-04-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('approve_article', 'Puede aprobar artículos'), ('feature_article', 'Puede destacar artículos')]},
        ),
    ]
