# Generated by Django 5.2 on 2025-04-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'permissions': [('can_vote', 'Puede votar')]},
        ),
    ]
